version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/kimby-playground/dist
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/kimby-playground/dist
    owner: root
    group: root
    mode: 755
